"""autogenerated by genmsg_py from simulator_stepRequest.msg. Do not edit."""
import roslib.message
import struct

import water_simulation.msg

class simulator_stepRequest(roslib.message.Message):
  _md5sum = "142f92320cf4b91d64d7813dc0575cb1"
  _type = "water_simulation/simulator_stepRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id
int32 iteration_cnt
msg_source_sink[] sources_sinks

================================================================================
MSG: water_simulation/msg_source_sink
float32 x
float32 y
float32 height
float32 radius
bool source  # if false, height is ignored and all water in this area is ignored
"""
  __slots__ = ['id','iteration_cnt','sources_sinks']
  _slot_types = ['int32','int32','water_simulation/msg_source_sink[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       id,iteration_cnt,sources_sinks
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(simulator_stepRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.iteration_cnt is None:
        self.iteration_cnt = 0
      if self.sources_sinks is None:
        self.sources_sinks = []
    else:
      self.id = 0
      self.iteration_cnt = 0
      self.sources_sinks = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.id, _x.iteration_cnt))
      length = len(self.sources_sinks)
      buff.write(_struct_I.pack(length))
      for val1 in self.sources_sinks:
        _x = val1
        buff.write(_struct_4fB.pack(_x.x, _x.y, _x.height, _x.radius, _x.source))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.id, _x.iteration_cnt,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sources_sinks = []
      for i in range(0, length):
        val1 = water_simulation.msg.msg_source_sink()
        _x = val1
        start = end
        end += 17
        (_x.x, _x.y, _x.height, _x.radius, _x.source,) = _struct_4fB.unpack(str[start:end])
        val1.source = bool(val1.source)
        self.sources_sinks.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.id, _x.iteration_cnt))
      length = len(self.sources_sinks)
      buff.write(_struct_I.pack(length))
      for val1 in self.sources_sinks:
        _x = val1
        buff.write(_struct_4fB.pack(_x.x, _x.y, _x.height, _x.radius, _x.source))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.id, _x.iteration_cnt,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sources_sinks = []
      for i in range(0, length):
        val1 = water_simulation.msg.msg_source_sink()
        _x = val1
        start = end
        end += 17
        (_x.x, _x.y, _x.height, _x.radius, _x.source,) = _struct_4fB.unpack(str[start:end])
        val1.source = bool(val1.source)
        self.sources_sinks.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2i = struct.Struct("<2i")
_struct_4fB = struct.Struct("<4fB")
"""autogenerated by genmsg_py from simulator_stepResponse.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg
import sensor_msgs.msg

class simulator_stepResponse(roslib.message.Message):
  _md5sum = "57396a8d7ecddc4299f990cc65ef0b10"
  _type = "water_simulation/simulator_stepResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool valid_id
sensor_msgs/Image water_img

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in src/image_encodings.cpp

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['valid_id','water_img']
  _slot_types = ['bool','sensor_msgs/Image']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       valid_id,water_img
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(simulator_stepResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.valid_id is None:
        self.valid_id = False
      if self.water_img is None:
        self.water_img = sensor_msgs.msg.Image()
    else:
      self.valid_id = False
      self.water_img = sensor_msgs.msg.Image()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_B3I.pack(_x.valid_id, _x.water_img.header.seq, _x.water_img.header.stamp.secs, _x.water_img.header.stamp.nsecs))
      _x = self.water_img.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.water_img.height, _x.water_img.width))
      _x = self.water_img.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.water_img.is_bigendian, _x.water_img.step))
      _x = self.water_img.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.water_img is None:
        self.water_img = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.valid_id, _x.water_img.header.seq, _x.water_img.header.stamp.secs, _x.water_img.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.valid_id = bool(self.valid_id)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.water_img.height, _x.water_img.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.water_img.is_bigendian, _x.water_img.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.data = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_B3I.pack(_x.valid_id, _x.water_img.header.seq, _x.water_img.header.stamp.secs, _x.water_img.header.stamp.nsecs))
      _x = self.water_img.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.water_img.height, _x.water_img.width))
      _x = self.water_img.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.water_img.is_bigendian, _x.water_img.step))
      _x = self.water_img.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.water_img is None:
        self.water_img = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.valid_id, _x.water_img.header.seq, _x.water_img.header.stamp.secs, _x.water_img.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.valid_id = bool(self.valid_id)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.water_img.height, _x.water_img.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.water_img.is_bigendian, _x.water_img.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.water_img.data = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_BI = struct.Struct("<BI")
_struct_B3I = struct.Struct("<B3I")
_struct_2I = struct.Struct("<2I")
class simulator_step(roslib.message.ServiceDefinition):
  _type          = 'water_simulation/simulator_step'
  _md5sum = '548ae3d80ba45ecbc6aaa72d202ee15d'
  _request_class  = simulator_stepRequest
  _response_class = simulator_stepResponse
